// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package toolsmock

import (
	"context"

	"github.com/slok/sloth/internal/http/backend/app"
	mock "github.com/stretchr/testify/mock"
)

// NewSLOGetter creates a new instance of SLOGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSLOGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SLOGetter {
	mock := &SLOGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SLOGetter is an autogenerated mock type for the SLOGetter type
type SLOGetter struct {
	mock.Mock
}

type SLOGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *SLOGetter) EXPECT() *SLOGetter_Expecter {
	return &SLOGetter_Expecter{mock: &_m.Mock}
}

// GetSLO provides a mock function for the type SLOGetter
func (_mock *SLOGetter) GetSLO(ctx context.Context, req app.GetSLORequest) (*app.GetSLOResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetSLO")
	}

	var r0 *app.GetSLOResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.GetSLORequest) (*app.GetSLOResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.GetSLORequest) *app.GetSLOResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.GetSLOResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.GetSLORequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SLOGetter_GetSLO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSLO'
type SLOGetter_GetSLO_Call struct {
	*mock.Call
}

// GetSLO is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.GetSLORequest
func (_e *SLOGetter_Expecter) GetSLO(ctx interface{}, req interface{}) *SLOGetter_GetSLO_Call {
	return &SLOGetter_GetSLO_Call{Call: _e.mock.On("GetSLO", ctx, req)}
}

func (_c *SLOGetter_GetSLO_Call) Run(run func(ctx context.Context, req app.GetSLORequest)) *SLOGetter_GetSLO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.GetSLORequest
		if args[1] != nil {
			arg1 = args[1].(app.GetSLORequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SLOGetter_GetSLO_Call) Return(getSLOResponse *app.GetSLOResponse, err error) *SLOGetter_GetSLO_Call {
	_c.Call.Return(getSLOResponse, err)
	return _c
}

func (_c *SLOGetter_GetSLO_Call) RunAndReturn(run func(ctx context.Context, req app.GetSLORequest) (*app.GetSLOResponse, error)) *SLOGetter_GetSLO_Call {
	_c.Call.Return(run)
	return _c
}

// NewSLOLister creates a new instance of SLOLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSLOLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *SLOLister {
	mock := &SLOLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SLOLister is an autogenerated mock type for the SLOLister type
type SLOLister struct {
	mock.Mock
}

type SLOLister_Expecter struct {
	mock *mock.Mock
}

func (_m *SLOLister) EXPECT() *SLOLister_Expecter {
	return &SLOLister_Expecter{mock: &_m.Mock}
}

// ListSLOs provides a mock function for the type SLOLister
func (_mock *SLOLister) ListSLOs(ctx context.Context, req app.ListSLOsRequest) (*app.ListSLOsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListSLOs")
	}

	var r0 *app.ListSLOsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListSLOsRequest) (*app.ListSLOsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListSLOsRequest) *app.ListSLOsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.ListSLOsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListSLOsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SLOLister_ListSLOs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSLOs'
type SLOLister_ListSLOs_Call struct {
	*mock.Call
}

// ListSLOs is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.ListSLOsRequest
func (_e *SLOLister_Expecter) ListSLOs(ctx interface{}, req interface{}) *SLOLister_ListSLOs_Call {
	return &SLOLister_ListSLOs_Call{Call: _e.mock.On("ListSLOs", ctx, req)}
}

func (_c *SLOLister_ListSLOs_Call) Run(run func(ctx context.Context, req app.ListSLOsRequest)) *SLOLister_ListSLOs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListSLOsRequest
		if args[1] != nil {
			arg1 = args[1].(app.ListSLOsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SLOLister_ListSLOs_Call) Return(listSLOsResponse *app.ListSLOsResponse, err error) *SLOLister_ListSLOs_Call {
	_c.Call.Return(listSLOsResponse, err)
	return _c
}

func (_c *SLOLister_ListSLOs_Call) RunAndReturn(run func(ctx context.Context, req app.ListSLOsRequest) (*app.ListSLOsResponse, error)) *SLOLister_ListSLOs_Call {
	_c.Call.Return(run)
	return _c
}
